
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class ManageStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentForm
     */
    Student std = new Student();
    DefaultTableModel model;
    public ManageStudentForm() {
        initComponents();
        std.fillStudent(jTable2, "");
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton1_female);
        bg.add(jRadioButton2_male);
        model = (DefaultTableModel)jTable2.getModel();
        jTable2.setRowHeight(40);
        jTable2.setShowGrid(true);
        jTable2.setGridColor(Color.blue);
        jTable2.setSelectionBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jRadioButton1_female = new javax.swing.JRadioButton();
        jRadioButton2_male = new javax.swing.JRadioButton();
        jDateChooser_birthdate = new com.toedter.calendar.JDateChooser();
        jTextField1_phone = new javax.swing.JTextField();
        jTextField1_lastname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_address = new javax.swing.JTextArea();
        jButton1_remove = new javax.swing.JButton();
        jButton1_add1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_firstname1 = new javax.swing.JTextField();
        jButton1_edit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1_value = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manage Student");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("FirstName");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("LastName");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("BirthDate");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Address");

        jTextField1_id.setEditable(false);

        jRadioButton1_female.setText("Female");

        jRadioButton2_male.setText("Male");

        jTextField1_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_phoneActionPerformed(evt);
            }
        });
        jTextField1_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1_phoneKeyTyped(evt);
            }
        });

        jTextField1_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_lastnameActionPerformed(evt);
            }
        });

        jTextArea1_address.setColumns(20);
        jTextArea1_address.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_address);

        jButton1_remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1_remove.setText("Remove");
        jButton1_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_removeActionPerformed(evt);
            }
        });

        jButton1_add1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1_add1.setText("Add");
        jButton1_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Student Id");

        jButton1_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1_edit.setText("Edit");
        jButton1_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_editActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FirstName", "Lastname", "Gender", "BirthDate", "Phone", "Address"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jTextField1_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_valueKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_valueKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1_valueKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Enter the Value to Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(357, 357, 357))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1_phone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser_birthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1_female, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2_male, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField1_lastname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1_firstname1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1_value, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_value, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1_firstname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1_female)
                            .addComponent(jRadioButton2_male)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_phoneActionPerformed

    }//GEN-LAST:event_jTextField1_phoneActionPerformed

    private void jTextField1_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_phoneKeyTyped
        //       allow only Numbers
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1_phoneKeyTyped

    private void jTextField1_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_lastnameActionPerformed

    private void jButton1_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_removeActionPerformed
      
//        when we delete a student record we must delete all scores affected to the student
//        we have to add a constraint to score table to do this 
//        constraint -> foreign key + on delete cascade

            /*           
            ALTER TABLE score 
            ADD CONSTRAINT fk_score_student 
            FOREIGN KEY (student_id) 
            REFERENCES student (Id) 
            ON DELETE CASCADE;

            */
        if(jTextField1_id.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "NO Student Selected");
        }
        else
        {
            int id = Integer.valueOf(jTextField1_id.getText());
            std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
            std.fillStudent(jTable2, "");
            jTable2.setModel(new DefaultTableModel(null,new Object[]{"ID","FirstName","Lastname","Gender","BirthDate","Phone","Address"}));
            std.fillStudent(jTable2, jTextField1_value.getText());
            MainForm.jLabel_studentCount.setText(" Student Count = "+Integer.toString(MyFunction.countData("student")));
            
            jTextField1_id.setText("");
            jTextArea1_address.setText("");
            jTextField1_firstname1.setText("");
            jTextField1_lastname.setText("");
            jTextField1_phone.setText("");
            jRadioButton2_male.setSelected(false);
            jRadioButton1_female.setSelected(false);
            jDateChooser_birthdate.setDate(null);
            

        }      
    }//GEN-LAST:event_jButton1_removeActionPerformed

    private void jButton1_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add1ActionPerformed
                    AddStudentForm Addsf = new AddStudentForm();
                    Addsf.setVisible(true);
                    Addsf.pack();
                    Addsf.setLocationRelativeTo(null);
                    Addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton1_add1ActionPerformed

    public boolean verifText()
    {
        if(jTextField1_firstname1.getText().equals("") || jTextField1_lastname.getText().equals("") 
           || jTextField1_phone.getText().equals("") || jTextArea1_address.getText().equals("") 
           || jTextField1_id.getText().equals("") || jDateChooser_birthdate.getDate() == null )
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Fields");
            return false;
        }
//        choose a date higher then current date 
        else if(jDateChooser_birthdate.getDate().compareTo(new Date()) > 0)
        {
            JOptionPane.showMessageDialog(null, "Invalid Date!");
            return false;
        }
        else
        {
            return true;
        }
    }
    private void jButton1_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_editActionPerformed
        String fname = jTextField1_firstname1.getText();
        String lname = jTextField1_lastname.getText();
        String phone = jTextField1_phone.getText();
        String address = jTextArea1_address.getText();
        int id = Integer.valueOf(jTextField1_id.getText());
        String gender = "";
        if(jRadioButton2_male.isSelected())
        {
            gender = "Male";
        }
        else if(jRadioButton1_female.isSelected())
        {
            gender = "Female";
        }
        
        if(verifText())
        {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(jDateChooser_birthdate.getDate());
            Student std = new Student();
            std.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, address);
//            MainForm.jLabel_studentCount.setText(" Student Count = "+Integer.toString(MyFunction.countData("student")));
         
//            refresh jTable
                ManageStudentForm.jTable2.setModel(new DefaultTableModel(null,new Object[]{"ID","FirstName","Lastname","Gender","BirthDate","Phone","Address"}));
                std.fillStudent(ManageStudentForm.jTable2, "");
        }
        
    }//GEN-LAST:event_jButton1_editActionPerformed
        int rowIndex;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        rowIndex = jTable2.getSelectedRow();
        
        
        if(model.getValueAt(rowIndex, 3).toString().equals("Female"))
        {
            jRadioButton1_female.setSelected(true);
            jRadioButton2_male.setSelected(false);
        }
        else
        {
            jRadioButton2_male.setSelected(true);
            jRadioButton1_female.setSelected(false);
        }
        jTextField1_id.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField1_firstname1.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField1_lastname.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField1_phone.setText(model.getValueAt(rowIndex, 5).toString());
        jTextArea1_address.setText(model.getValueAt(rowIndex, 6).toString());
        
        Date bdate;
        try {
            bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooser_birthdate.setDate(bdate);
        
        } catch (ParseException ex) {
            Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField1_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_valueKeyTyped
        
    }//GEN-LAST:event_jTextField1_valueKeyTyped

    private void jTextField1_valueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_valueKeyPressed
        
    }//GEN-LAST:event_jTextField1_valueKeyPressed

    private void jTextField1_valueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_valueKeyReleased
       jTable2.setModel(new DefaultTableModel(null,new Object[]{"ID","FirstName","Lastname","Gender","BirthDate","Phone","Address"}));
        std.fillStudent(jTable2, jTextField1_value.getText());
    }//GEN-LAST:event_jTextField1_valueKeyReleased

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            rowIndex = jTable2.getSelectedRow();
            jTextField1_id.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField1_firstname1.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField1_lastname.setText(model.getValueAt(rowIndex, 2).toString());
            jTextField1_phone.setText(model.getValueAt(rowIndex, 5).toString());
            jTextArea1_address.setText(model.getValueAt(rowIndex, 6).toString());
        
            if(model.getValueAt(rowIndex, 3).toString().equals("Female"))
            {
                jRadioButton1_female.setSelected(true);
                jRadioButton2_male.setSelected(false);
            }
            else
            {
                jRadioButton2_male.setSelected(true);
                jRadioButton1_female.setSelected(false);
            }
        
            Date bdate;
            try {
                bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                jDateChooser_birthdate.setDate(bdate);
        
                } catch (ParseException ex) {
                Logger.getLogger(ManageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
        
    }//GEN-LAST:event_jTable2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add1;
    private javax.swing.JButton jButton1_edit;
    private javax.swing.JButton jButton1_remove;
    private com.toedter.calendar.JDateChooser jDateChooser_birthdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_female;
    private javax.swing.JRadioButton jRadioButton2_male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1_address;
    private javax.swing.JTextField jTextField1_firstname1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_lastname;
    private javax.swing.JTextField jTextField1_phone;
    private javax.swing.JTextField jTextField1_value;
    // End of variables declaration//GEN-END:variables
}
